camel:
  springboot:
    main-run-controller: true
  component:
    aws2-s3.accessKey: XXXX
    aws2-s3.secretKey: XXXXX
    aws2-s3.region: us-east-1

folderWatch:
  directory:  d://inbox
  pollingFrequency: 5000


awsS3BucketName: arn:aws:s3:::XXX
awsAccessKey: XXXXX
awsAccessKeySecret: XXXXX