camel:
  springboot:
    main-run-controller: true
  component:
    aws2-s3.accessKey: X
    aws2-s3.secretKey: XXXXX
    aws2-s3.region: us-east-1

folderWatch:
  directory:  d://inbox
  pollingFrequency: 5000


aws:
  s3:
    access_key_id: XXXX
    secret_access_key: XXXX
    region: us-east-1
    endpointUrl: https://s3.us-east-1.amazonaws.com
    bucket: <bucket-name>

awsS3BucketName: arn:aws:s3:::<bucket-name>
awsAccessKey: XXXX
awsAccessKeySecret: XXXX